#마인크래프트 내에서 tab 키를 누를시 보이는 탭리스트를 커스텀하는 코드입니다.
#6번째 라인을 수정해서 사용하시면 됩니다.

every 3 seconds:
	loop all players:
		set tab header to "                                                                                                                                   %nl%(서버이름)&a&l서버에 오신걸 환영합니다! %nl%" and footer to "%nl% &3&l현재 시각: %now% %nl% &f서버 접속자 수: &e%number of all players% %nl% &f서버 주소: &b&l(서버주소)%nl%" for loop-players 
